[package]
name = "folding_range"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
ast.workspace = true
lsp-types.workspace = true

[dev-dependencies]
expect-test.workspace = true
