[package]
name = "definition"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
ast.workspace = true
call_chain.workspace = true
dto.workspace = true
document.workspace = true
local_variable.workspace = true
lsp-types.workspace = true
lsp_extra.workspace = true
my_string.workspace = true
position.workspace = true
tyres.workspace = true
hover.workspace = true

[dev-dependencies]
variables.workspace = true
imports.workspace = true
parser.workspace = true
expect-test.workspace = true
