[package]
name = "cli"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
config.workspace = true
ast.workspace = true
formatter.workspace = true
jdk.workspace = true
editorconfig.workspace = true

