[package]
name = "project"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
common.workspace = true
lsp-types.workspace = true
lsp-server.workspace = true
lsp_extra.workspace = true
my_string.workspace = true
maven.workspace = true
gradle.workspace = true
tokio.workspace = true
dto.workspace = true
workspace_hack = { version = "0.1", path = "../workspace_hack" }
