[package]
name = "gradle"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true
compile.workspace = true
common.workspace = true
maven.workspace = true
dto.workspace = true
loader.workspace = true
my_string.workspace = true

[dev-dependencies]
expect-test.workspace = true
