[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
nom.workspace = true
dashmap.workspace = true
parser = { path = "../parser"}


[dev-dependencies]
pretty_assertions.workspace = true
