[package]
name = "code_lens"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
ast.workspace = true
common.workspace = true
config.workspace = true
document_link.workspace = true
lsp_extra.workspace = true
lsp-types.workspace = true
my_string.workspace = true
serde_json.workspace = true
command.workspace = true
