[package]
name = "imports"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
my_string.workspace = true
ast.workspace = true
dto.workspace = true
