[package]
name = "my_string"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
arbitrary = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
expect-test.workspace = true
