[package]
name = "decompiler"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
my_string.workspace = true
ast.workspace = true
mutf8.workspace = true
bitflags.workspace = true

[dev-dependencies]
expect-test.workspace = true
formatter.workspace = true
editorconfig.workspace = true

