[package]
name = "lsp_extra"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
my_string.workspace = true
tokio.workspace = true
lsp-types.workspace = true
lsp-server.workspace = true
ast.workspace = true
serde_json.workspace = true
common.workspace = true
