[package]
name = "command"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
my_string.workspace = true
common.workspace = true
dto.workspace = true
gradle.workspace = true
maven.workspace = true
lsp_extra.workspace = true
lsp-types.workspace = true
lsp-server.workspace = true
serde_json.workspace = true
tokio.workspace = true
dirs.workspace = true
project.workspace = true
