[package]
name = "server"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true
lsp-server.workspace = true
lsp-types.workspace = true
serde_json.workspace = true
formatter.workspace = true
dto.workspace = true
parser.workspace = true
loader.workspace = true
maven.workspace = true
gradle.workspace = true
imports.workspace = true
position.workspace = true
document.workspace = true
variables.workspace = true
jdk.workspace = true
compile.workspace = true
call_chain.workspace = true
common.workspace = true
config.workspace = true
my_string.workspace = true
lsp_extra.workspace = true
editorconfig.workspace = true
hover.workspace = true
definition.workspace = true
code_action.workspace = true
document_link.workspace = true
completion.workspace = true
inlay_hint.workspace = true
folding_range.workspace = true
code_lens.workspace = true
command.workspace = true
project.workspace = true
signature.workspace = true
references.workspace = true
workspace_hack = { version = "0.1", path = "../workspace_hack" }
