name: ast-check-jdk
on:
  pull_request:
  push:
    branches:
      - main
      - ast_migration

jobs:
  build:
    name: Build and ast check jdk
    runs-on: ubuntu-latest
    if: github.repository == 'emilycares/java_lsp'
    steps:
      - uses: actions/checkout@v5
      - uses: nixbuild/nix-quick-install-action@v34
      - run: nix build --version
      - run: nix develop .#check_jdk --command bash -c "java_lsp ast-check-jdk"
